arches:
- x86_64
stages:
- image: registry.access.redhat.com/ubi8/go-toolset:1.25@sha256:070a8b01fe3c47cda74390c49c37e0abde1157c162cc3a46be1698564a18f923
  packages:
    - git
    - bash
    - openssh
    - gcc
    - tzdata
    - cmake
    - clang
    - openssl
- image: registry.redhat.io/ubi8/ubi-minimal@sha256:5dc6ba426ccbeb3954ead6b015f36b4a2d22320e5b356b074198d08422464ed2
  packages:
    - ca-certificates
    - wget
