arches:
- x86_64
stages:
# Dockerfile.konflux.api, builder step
- image: registry.access.redhat.com/ubi8/go-toolset:1.25@sha256:d3086455658222fcb72fe73c255f10400cc3524faa914dc2a4ecdb4973f5cd27
  packages:
  - cmake
  - clang
  - openssl
# Dockerfile.konflux.api final step
- image: registry.redhat.io/ubi8/ubi-minimal@sha256:6ed9271b3d3e7147728afaf8917a936c0db2f1badba59550288c2cc772afb58f
  packages:
  - ca-certificates
  - wget
