arches:
- x86_64
- aarch64
- ppc64le
stages:
- image: registry.redhat.io/ubi9/python-312:1@sha256:99f6d9e3d833b0b35db30f53a104846d7e4f811531d16602b2867dcfeed9a17b
  packages:
    - skopeo
    - gcc
    - gcc-c++
    - python3.12-devel
    - redhat-rpm-config
    - make
    - cmake
    - ninja-build
